version: '1'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:latest
    container_name: alexon-database-container
    restart: unless-stopped
    tty: true
    ports:
     - "33069:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: alexon-database
      MYSQL_USER: abdelrhman
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
